name: Build and push Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "* 0 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check for UNS update
        run: |
          sudo /bin/sh -c "echo 'deb [ trusted=yes arch=amd64,arm64 ] https://www.ui.com/downloads/unifi/debian stable ubiquiti' > /etc/apt/sources.list.d/100-ubnt-unifi.list"
          sudo apt update
          export repo_version=$(apt info unifi 2>/dev/null | grep '^Version: ' | cut -d' ' -f2)
          export local_version=$(cat current_uns_version)
          if [[ "$repo_version" == "$local_version" ]]
          then
            echo "Already up-to-date with version $local_version"
            "::set-output name=should_continue::false"
          else
            "::set-output name=should_continue::true"
            echo "New version detected.  Current: $local_version. New: $repo_version"
            echo "Continuing with build."
            echo "UNIFI_REPO_VERSION=$repo_version" >> $GITHUB_ENV
          fi
      
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true
          
      - name: Set up QEMU
        if: steps.check_condition.outputs.should_continue == 'true'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: armhf
          
      - name: Set up Docker Buildx
        if: steps.check_condition.outputs.should_continue == 'true'
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/armhf
      
      - name: Login to Docker Hub
        if: steps.check_condition.outputs.should_continue == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        if: steps.check_condition.outputs.should_continue == 'true'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/armhf
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/unifi-cloudkey:latest
            ${{ vars.DOCKERHUB_USERNAME }}/unifi-cloudkey:${{ env.UNIFI_REPO_VERSION }}

      - uses: actions/checkout@v3
      - name: Update local version
        if: steps.check_condition.outputs.should_continue == 'true'
        run: |
          apt info unifi 2>/dev/null | grep '^Version: ' | cut -d' ' -f2 > current_uns_version
      - name: Commit new UNS version
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_message: "Updating UNS version number"
          force: false      

